export const REPORTING_ANALYTICS_REPOSITORY = Symbol("REPORTING_ANALYTICS_REPOSITORY");
export const REPORTING_ANALYTICS_SERVICE = Symbol("REPORTING_ANALYTICS_SERVICE");
export const REPORTING_ANALYTICS_ORDERS = Symbol("REPORTING_ANALYTICS_ORDERS");
export const REPORTING_ANALYTICS_STORE_RESOLVER = Symbol(
  "REPORTING_ANALYTICS_STORE_RESOLVER",
);
