export const DIRECT_PAYMENT_REPOSITORY = Symbol("DIRECT_PAYMENT_REPOSITORY");
export const DIRECT_PAYMENT_PROVIDER = Symbol("DIRECT_PAYMENT_PROVIDER");
export const DIRECT_PAYMENT_SERVICE = Symbol("DIRECT_PAYMENT_SERVICE");
export const SELLER_STORE_RESOLVER = Symbol("SELLER_STORE_RESOLVER");
