export const DIRECT_PAYMENT_REPOSITORY = Symbol("DIRECT_PAYMENT_REPOSITORY");
export const DIRECT_PAYMENT_PROVIDER = Symbol("DIRECT_PAYMENT_PROVIDER");
export const DIRECT_PAYMENT_SERVICE = Symbol("DIRECT_PAYMENT_SERVICE");
export const PAYMENT_REVIEW_AUTHORIZER = Symbol("PAYMENT_REVIEW_AUTHORIZER");
