export const CART_REPOSITORY = Symbol("CART_REPOSITORY");
export const CART_SERVICE = Symbol("CART_SERVICE");
export const SAVED_ADDRESS_REPOSITORY = Symbol("SAVED_ADDRESS_REPOSITORY");
export const SAVED_ADDRESS_SERVICE = Symbol("SAVED_ADDRESS_SERVICE");
export const CHECKOUT_REPOSITORY = Symbol("CHECKOUT_REPOSITORY");
export const CHECKOUT_SERVICE = Symbol("CHECKOUT_SERVICE");
export const SELLER_ORDER_STORE_RESOLVER = Symbol("SELLER_ORDER_STORE_RESOLVER");
