export const CART_REPOSITORY = Symbol("CART_REPOSITORY");
export const CART_SERVICE = Symbol("CART_SERVICE");
export const SAVED_ADDRESS_REPOSITORY = Symbol("SAVED_ADDRESS_REPOSITORY");
export const SAVED_ADDRESS_SERVICE = Symbol("SAVED_ADDRESS_SERVICE");
