export const STORE_FOLLOWING_SERVICE = Symbol("STORE_FOLLOWING_SERVICE");
export const DISCOVERY_FEED_REPOSITORY = Symbol("DISCOVERY_FEED_REPOSITORY");
export const DISCOVERY_FEED_PRODUCT_READ = Symbol("DISCOVERY_FEED_PRODUCT_READ");
export const DISCOVERY_FEED_SERVICE = Symbol("DISCOVERY_FEED_SERVICE");
export const FOLLOWING_FEED_SERVICE = Symbol("FOLLOWING_FEED_SERVICE");
