export const IDENTITY_ACCESS_REPOSITORY = Symbol("IDENTITY_ACCESS_REPOSITORY");
export const OTP_PROVIDER = Symbol("OTP_PROVIDER");
export const IDENTITY_OTP_SERVICE = Symbol("IDENTITY_OTP_SERVICE");
export const RUNTIME_ENVIRONMENT = Symbol("RUNTIME_ENVIRONMENT");
