export const IDENTITY_ACCESS_REPOSITORY = Symbol("IDENTITY_ACCESS_REPOSITORY");
export const OTP_PROVIDER = Symbol("OTP_PROVIDER");
export const IDENTITY_OTP_SERVICE = Symbol("IDENTITY_OTP_SERVICE");
export const SELLER_APPLICATION_APPLICANT = Symbol("SELLER_APPLICATION_APPLICANT");
export const SELLER_APPLICATION_REPOSITORY = Symbol("SELLER_APPLICATION_REPOSITORY");
export const SELLER_APPLICATION_REVIEWER = Symbol("SELLER_APPLICATION_REVIEWER");
export const SELLER_APPROVAL_RECOVERY = Symbol("SELLER_APPROVAL_RECOVERY");
export const PLATFORM_AGENT_SESSION_AUTHORIZER = Symbol(
  "PLATFORM_AGENT_SESSION_AUTHORIZER",
);
export const PLATFORM_AGENT_OTP_SERVICE = Symbol("PLATFORM_AGENT_OTP_SERVICE");
export const RUNTIME_ENVIRONMENT = Symbol("RUNTIME_ENVIRONMENT");
