export const STORE_REPOSITORY = Symbol("STORE_REPOSITORY");
export const STORE_SERVICE = Symbol("STORE_SERVICE");
export const PUBLIC_STORE_FOLLOWING_READER = Symbol("PUBLIC_STORE_FOLLOWING_READER");
export const SETTLEMENT_DESTINATION_VERIFIER = Symbol(
  "SETTLEMENT_DESTINATION_VERIFIER",
);
