export const STORE_REPOSITORY = Symbol("STORE_REPOSITORY");
export const STORE_SERVICE = Symbol("STORE_SERVICE");
export const SETTLEMENT_DESTINATION_VERIFIER = Symbol(
  "SETTLEMENT_DESTINATION_VERIFIER",
);
